### ISSUE TITLE
Segfault in PreFilter

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-k8s#80]
The current CI tests are failing because:

```console
UTC (now=2024-08-04 08:16:43.110414282 +0000 UTC))"
E0804 08:16:43.110598       1 panic.go:261] "Observed a panic" panic="runtime error: invalid memory address or nil pointer dereference" panicGoValue="\"invalid memory address or nil pointer dereference\"" stacktrace=<
        goroutine 455 [running]:
        k8s.io/apimachinery/pkg/util/runtime.logPanic({0x2aeaac8, 0x4146560}, {0x2303840, 0x408f170})
                k8s.io/apimachinery/pkg/util/runtime/runtime.go:107 +0xbc
        k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x2aeaac8, 0x4146560}, {0x2303840, 0x408f170}, {0x4146560, 0x0, 0x100000000000000?})
                k8s.io/apimachinery/pkg/util/runtime/runtime.go:82 +0x5e
        k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
                k8s.io/apimachinery/pkg/util/runtime/runtime.go:59 +0x108
        panic({0x2303840?, 0x408f170?})
                runtime/panic.go:770 +0x132
        k8s.io/kubernetes/pkg/scheduler/framework/plugins/fluence.(*Fluence).PreFilter(0xc000a16700, {0x2aeac28, 0xc000c75950}, 0xc000976280, 0xc000025688)
                k8s.io/kubernetes/pkg/scheduler/framework/plugins/fluence/fluence.go:232 +0x7
```

The part in the code:

```go
	if node != "" {
		fluence.log.Info("[Fluence PreFilter] assigned pod %s to node %s\n", pod.Name, node)
		result := framework.PreFilterResult{NodeNames: sets.New(node)}
		return &result, framework.NewStatus(framework.Success, "")
	}
```
And specifically this line:

```go
		fluence.log.Info("[Fluence PreFilter] assigned pod %s to node %s\n", pod.Name, node)
```
My best guess is that something changed in upstream so that PreFilter is providing a pod that is undefined, at least I don't see any issue with the sting. The logs are really hard to get with fluence given that the container crashes - will need to probably approach this from reading code tomorrow (or later... probably there isn't huge rush on this).

**Comment by vsoch** [comment]
I forget if we resolved this error (I think we did) but I didn't close the issue so I'll report on the recent failure. It looks like fluence starts OK, but since the base image was changed [from alpine](https://github.com/kubernetes-sigs/scheduler-plugins/blob/4a00cfd583d53118642925523bd0546bce76bb90/build/scheduler/Dockerfile#L25) to distroless, we no longer have our simple logging strategy to write to /tmp/fluence.log so it's impossible to see. I moved the Dockerfile for the scheduler to be under our control and removed the multistage build (which should not be a big deal, the image is already tiny) and the error I'm seeing now is about an interface conversion:

```go
	----Match Allocate output---
jobid: 1
reserved: false
I1006 21:34:51.208496       1 fluxion.go:91] [Fluence] There are no errors
allocated: {"graph": {"nodes": [{"id": "3", "metadata": {"type": "core", "id": 0, "rank": -1, "exclusive": true, "paths": {"containment": "/k8scluster0/0/kind-worker1/core0"}}}, {"id": "2", "metadata": {"type": "node", "basename": "kind-worker", "id": 1, "rank": -1, "paths": {"containment": "/k8scluster0/0/kind-worker1"}}}, {"id": "1", "metadata": {"type": "subnet", "basename": "", "id": 0, "rank": -1, "paths": {"containment": "/k8scluster0/0"}}}, {"id": "0", "metadata": {"type": "cluster", "basename": "k8scluster", "id": 0, "rank": -1, "paths": {"containment": "/k8scluster0"}}}], "edges": [{"source": "2", "target": "3"}, {"source": "1", "target": "2"}, {"source": "0", "target": "1"}]}}

at: 0
overhead: 0.000356
panic: interface conversion: interface {} is nil, not string

goroutine 41 [running]:
github.com/flux-framework/flux-k8s/flux-plugin/fluence/utils.ParseAllocResult({0xc000016000, 0x2ad}, {0xc0004ae690, 0x29})
	/go/src/fluence/utils/utils.go:295 +0x785
github.com/flux-framework/flux-k8s/flux-plugin/fluence/fluxion.(*Fluxion).Match(0xc0003b2be0, {0x12b5420?, 0xc00009aad8?}, 0xc000112730)
	/go/src/fluence/fluxion/fluxion.go:110 +0x2a8
github.com/flux-framework/flux-k8s/flux-plugin/fluence/fluxcli-grpc._FluxcliService_Match_Handler({0x12b5420, 0xc0003b2be0}, {0x15f4dc8, 0xc0001ac7e0}, 0xc00010e6c0, 0x0)
	/go/src/fluence/fluxcli-grpc/fluxcli_grpc.pb.go:95 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000448c40, {0x15f9b18, 0xc000002000}, 0xc00033a240, 0xc0001ac510, 0x1f17240, 0x0)
	/go/src/fluence/vendor/google.golang.org/grpc/server.go:1286 +0xc5e
google.golang.org/grpc.(*Server).handleStream(0xc000448c40, {0x15f9b18, 0xc000002000}, 0xc00033a240, 0x0)
	/go/src/fluence/vendor/google.golang.org/grpc/server.go:1609 +0x9da
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/src/fluence/vendor/google.golang.org/grpc/server.go:934 +0x8d
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 57
	/go/src/fluence/vendor/google.golang.org/grpc/server.go:932 +0x226
```
There are likely two errors here - the log silently failing to write (and possibly not allowing things to proceed) and then this new error. I'll debug and open a PR if I figure it out.
